"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Navigation } from "@/components/navigation";
import { Footer } from "@/components/footer";

export default function DownloadLlmsPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { data: session, status } = useSession();
  const [downloading, setDownloading] = useState(false);
  const [paid, setPaid] = useState(false);
  const loading = status === "loading";
  const user = session?.user;

  useEffect(() => {
    const paidParam = searchParams?.get("paid");
    if (paidParam === "true") {
      setPaid(true);
    }

    if (!loading && !session) {
      router.push("/login?next=/download-llms");
    }
  }, [session, loading, router, searchParams]);

  const handleDownload = () => {
    setDownloading(true);
    
    // Generate llms.txt content
    const llmsTxtContent = `# llms.txt - LLM Optimization File
# Generated by LLMO Directory

# Site Information
Site: ${user?.email?.split("@")[1] || "yourdomain.com"}
Contact: ${user?.email || "contact@yourdomain.com"}

# Content Guidelines
- This site is optimized for AI readability
- Content is structured for LLM parsing
- Metadata is properly formatted

# Sitemap
# Add your sitemap URL here
# Sitemap: https://yourdomain.com/sitemap.xml

# Robots
# Add your robots.txt URL here
# Robots: https://yourdomain.com/robots.txt

# Additional Resources
# Add links to important pages, documentation, etc.
`;

    // Create blob and download
    const blob = new Blob([llmsTxtContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "llms.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setDownloading(false);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex flex-col">
        <Navigation />
        <main className="flex-1 container mx-auto px-4 py-8 flex items-center justify-center">
          <p className="font-mono text-muted-foreground">Loading...</p>
        </main>
        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />

      <main className="flex-1">
        <section className="container mx-auto px-4 py-12">
          <div className="max-w-3xl mx-auto">
            <div className="text-center mb-12">
              <p className="font-mono text-sm text-accent mb-3">// DOWNLOAD READY</p>
              <h1 className="font-mono text-3xl md:text-4xl font-bold mb-4">Your llms.txt File</h1>
              <p className="text-lg text-muted-foreground">
                Download your generated llms.txt file and follow the installation guide below
              </p>
            </div>

            <Card className="p-8 border-accent/50 mb-8">
              <div className="text-center mb-8">
                <div className="inline-block p-6 border-2 border-green-500/20 rounded-lg bg-green-500/10 mb-6">
                  <p className="font-mono text-2xl text-green-500 mb-2">✓</p>
                  <p className="font-mono text-sm text-muted-foreground">Payment Successful</p>
                </div>
                <p className="text-muted-foreground mb-6">
                  Your llms.txt file has been generated and is ready to download.
                </p>
                <Button
                  onClick={handleDownload}
                  disabled={downloading}
                  size="lg"
                  className="font-mono bg-accent text-accent-foreground hover:bg-accent/90 glow-accent"
                >
                  {downloading ? "Downloading..." : "Download llms.txt"}
                </Button>
              </div>
            </Card>

            <Card className="p-8 border-border">
              <div className="mb-6">
                <p className="font-mono text-sm text-accent mb-3">// INSTALLATION GUIDE</p>
                <h2 className="font-mono text-2xl font-bold mb-4">How to Install on Your Site</h2>
              </div>

              <div className="space-y-6">
                <div>
                  <h3 className="font-mono font-semibold mb-2 text-lg">Step 1: Upload the File</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed mb-2">
                    Upload the <code className="bg-muted px-1 py-0.5 rounded font-mono text-xs">llms.txt</code> file to
                    the root directory of your website (same location as your <code className="bg-muted px-1 py-0.5 rounded font-mono text-xs">robots.txt</code> file).
                  </p>
                  <p className="text-xs text-muted-foreground font-mono">
                    Example: https://yourdomain.com/llms.txt
                  </p>
                </div>

                <div>
                  <h3 className="font-mono font-semibold mb-2 text-lg">Step 2: Verify Access</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    After uploading, verify that the file is accessible by visiting{" "}
                    <code className="bg-muted px-1 py-0.5 rounded font-mono text-xs">https://yourdomain.com/llms.txt</code> in your browser.
                  </p>
                </div>

                <div>
                  <h3 className="font-mono font-semibold mb-2 text-lg">Step 3: Customize (Optional)</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    Edit the downloaded file to add your specific sitemap URLs, contact information, and any additional
                    resources you want AI systems to know about.
                  </p>
                </div>

                <div>
                  <h3 className="font-mono font-semibold mb-2 text-lg">Step 4: Test</h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    Use the{" "}
                    <Link href="/analyzer" className="text-accent hover:underline font-mono">
                      Analyzer
                    </Link>{" "}
                    tool again to verify that your site now scores higher.
                  </p>
                </div>
              </div>

              <div className="mt-8 pt-6 border-t border-border">
                <div className="p-4 bg-muted/30 rounded-lg">
                  <p className="font-mono text-xs text-muted-foreground mb-2">// TIP</p>
                  <p className="text-sm text-muted-foreground">
                    Keep your llms.txt file updated as you add new content or change your site structure. This helps AI
                    systems stay current with your content.
                  </p>
                </div>
              </div>
            </Card>

            <div className="mt-8 text-center">
              <Link href="/analyzer">
                <Button variant="outline" className="font-mono bg-transparent">
                  Analyze Another Site
                </Button>
              </Link>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}

